# Generated by Django 5.2.2 on 2025-12-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.CharField(max_length=2000),
        ),
    ]
