# Generated by Django 5.2.2 on 2025-12-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="Shift",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.CharField(default="best industry", max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.CharField(max_length=2000),
        ),
    ]
