# Generated by Django 5.2.2 on 2025-12-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_job_shift_job_salary_alter_job_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="exprience",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
