# Generated by Django 5.2.2 on 2025-12-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_job_exprience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.CharField(max_length=5000),
        ),
    ]
