# Generated by Django 5.2.2 on 2025-12-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_alter_job_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="Shift",
            field=models.CharField(default="Day", max_length=200),
        ),
        migrations.AlterField(
            model_name="job",
            name="exprience",
            field=models.CharField(default="Fresher", max_length=100),
        ),
    ]
